- name: Install basic software
  hosts: all
  tasks:
    - name: Update repositories cache and install deps
      apt:
        name:
          - git
          - python2
          - python3
          - curl
          - tmux
          - htop
          - python-pip
          - strace
          - mosh
          - golang
          - pipenv
          - vim-gtk
          - silversearcher-ag
          - nmap
          - hashid
        update_cache: yes


    - name: Get GPG keys for RVM install package
      shell: curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

    - name: Install RVM
      shell: curl -sSL https://get.rvm.io | bash -s stable
      args:
        warn: false

    - name: Install seclists wordlists
      shell: mkdir $HOME/Repos && mkdir -p /usr/share/wordlists
      git:
          repo: git@github.com:danielmiessler/SecLists.git
          dest: $HOME/Repos

    - name: Create seclists symlink
      shell: ln -s $HOME/Repos /usr/share/wordlists

    - name: Configure zsh autosuggest strategy
      shell: echo ZSH_AUTOSUGGEST_STRATEGY=match_prev_cmd >> ~/.zshrc.local

    - name: Configure zsh history dups
      shell: echo HIST_IGNORE_ALL_DUPS="false" >> ~/.zshrc.local && echo HIST_EXPIRE_DUPS_FIRST="true" >> ~/.zshrc.local

    - name: Configure zsh beeps
      shell: echo "unsetopt LIST_BEEP" >> ~/.zshrc.local

