---
- hosts: all
  vars:
    # your extra bundles here
    zsh_antigen_bundles_extras: [git]
    # your variables here
    zsh_autosuggestions_bind_key: "^U"
    zsh_antigen_theme: "pygmalion"
    zsh_aliases:
            - { alias: 'whats-my-ip', action: 'curl https://ipinfo.io/ip'}
            - { alias: 'glom', action: 'git pull origin master'}
            - { alias: 'glod', action: 'git pull origin develop'}
            - { alias: 'gcom', action: 'git checkout master'}
            - { alias: 'gcod', action: 'git checkout develop'}
            - { alias: 'webshare', action: 'python -m SimpleHTTPServer'}
            - { alias: 'pbcopy', action: 'xclip -sel clipboard'}
            - { alias: 'do-updates', action: 'sudo apt update && sudo apt full-upgrade'}
  roles:
    - viasite-ansible.zsh
